# Generated by Django 3.0.2 on 2020-04-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_Info',
            fields=[
                ('projectName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=3)),
                ('dmName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Dashboard_Info',
            },
        ),
    ]
