# Generated by Django 3.0.2 on 2020-05-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_info',
            name='completionZone',
            field=models.CharField(default='Green', max_length=10),
        ),
    ]
