# Generated by Django 3.0.2 on 2020-05-05 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0003_auto_20200504_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='totalSites',
            field=models.IntegerField(default=550),
        ),
        migrations.CreateModel(
            name='RagDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('windowsPlanned', models.IntegerField()),
                ('windowsCompleted', models.IntegerField()),
                ('openIssues', models.CharField(max_length=3)),
                ('custSatisfaction', models.IntegerField()),
                ('sitesCompleted', models.IntegerField()),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.ProjectDetails')),
            ],
            options={
                'db_table': 'RAGDetails',
            },
        ),
    ]
