# Generated by Django 3.0.2 on 2020-05-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0006_auto_20200507_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='endDate',
            field=models.CharField(default='June 2020', max_length=15),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='startDate',
            field=models.CharField(default='May 2020', max_length=15),
        ),
    ]
