# Generated by Django 3.0.2 on 2020-05-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0007_auto_20200510_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='endDate',
            field=models.CharField(default='June 2020', max_length=25),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='startDate',
            field=models.CharField(default='May 2020', max_length=25),
        ),
    ]
