# Generated by Django 3.0.2 on 2020-06-12 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0008_auto_20200510_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectPID', models.CharField(max_length=30)),
                ('dealValue', models.CharField(max_length=8)),
                ('cxDMName', models.CharField(max_length=100)),
                ('SDEName', models.CharField(max_length=100)),
                ('teamName', models.CharField(max_length=100)),
                ('reviewMonth', models.CharField(max_length=25)),
                ('startDate', models.CharField(max_length=25)),
                ('endDate', models.CharField(max_length=25)),
                ('executiveSummary', models.TextField()),
                ('customerSentiment', models.CharField(max_length=10)),
                ('overallStatus', models.CharField(max_length=10)),
                ('scheduleStatus', models.CharField(max_length=10)),
                ('scheduleComments', models.TextField()),
                ('qualityStatus', models.CharField(max_length=10)),
                ('qualityComments', models.TextField()),
                ('resourceStatus', models.CharField(max_length=10)),
                ('resourceComments', models.TextField()),
                ('automationStatus', models.CharField(max_length=10)),
                ('automationComments', models.TextField()),
                ('accomplishments', models.TextField()),
                ('goalsForNextMonth', models.TextField()),
                ('risksImpactAsks', models.TextField()),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.Dashboard_Info')),
            ],
            options={
                'db_table': 'project_review',
            },
        ),
    ]
