# Generated by Django 3.0.2 on 2021-09-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0010_resources_resourceskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='phoneNum',
            field=models.CharField(max_length=12),
        ),
    ]
