# Generated by Django 3.0.2 on 2021-09-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0011_auto_20210924_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceskills',
            name='assignedProject',
        ),
        migrations.AddField(
            model_name='resources',
            name='assignedProject',
            field=models.CharField(default='Morgan Stanley', max_length=50),
        ),
    ]
