# Generated by Django 3.0.2 on 2021-09-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0012_auto_20210924_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpTechnologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spRoutingSwitching', models.CharField(max_length=100)),
                ('spMplsL2L3Vpn', models.CharField(max_length=100)),
                ('spMplste', models.CharField(max_length=100)),
                ('spMulticastMultiCastVpn', models.CharField(max_length=100)),
                ('spXrHardwarePlatformsOs', models.CharField(max_length=100)),
                ('spNexusHardwarePlatformsOs', models.CharField(max_length=100)),
                ('spAccessPlatforms', models.CharField(max_length=100)),
                ('spSegmentRouting', models.CharField(max_length=100)),
                ('spSegmentRoutingSdnBgpPcep', models.CharField(max_length=100)),
                ('spSegmentRoutingTE', models.CharField(max_length=100)),
                ('spEvpnPbBEvpn', models.CharField(max_length=100)),
                ('spVxlan', models.CharField(max_length=100)),
                ('spNso', models.CharField(max_length=100)),
                ('cecId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.Resources')),
            ],
            options={
                'db_table': 'SpTechnologies',
            },
        ),
        migrations.CreateModel(
            name='ScriptingSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.CharField(max_length=20)),
                ('vbaScripting', models.CharField(max_length=20)),
                ('restApi', models.CharField(max_length=20)),
                ('jsonXml', models.CharField(max_length=20)),
                ('netconfRestconfYang', models.CharField(max_length=20)),
                ('cecId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.Resources')),
            ],
            options={
                'db_table': 'ScriptingSkills',
            },
        ),
        migrations.CreateModel(
            name='EntTechnologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entRouting', models.CharField(max_length=100)),
                ('entSwitching', models.CharField(max_length=100)),
                ('itilFoundation', models.CharField(max_length=50)),
                ('entOperationsTools', models.CharField(max_length=100)),
                ('entDesign', models.CharField(max_length=100)),
                ('entDnaSDA', models.CharField(max_length=100)),
                ('entMulticast', models.CharField(max_length=100)),
                ('entQos', models.CharField(max_length=100)),
                ('entDmvpn', models.CharField(max_length=100)),
                ('entMeraki', models.CharField(max_length=100)),
                ('entMultiCloud', models.CharField(max_length=100)),
                ('entSdn', models.CharField(max_length=100)),
                ('entIpv6', models.CharField(max_length=100)),
                ('cecId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.Resources')),
            ],
            options={
                'db_table': 'EntTechnologies',
            },
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=10)),
                ('amiFunction', models.CharField(max_length=15)),
                ('architecture', models.CharField(max_length=30)),
                ('subDomain', models.CharField(max_length=15)),
                ('technology', models.CharField(max_length=30)),
                ('qtr', models.CharField(max_length=10)),
                ('lifeCycleStage', models.CharField(max_length=50)),
                ('serviceDescription', models.CharField(max_length=50)),
                ('solutionTemplateDocument', models.CharField(max_length=50)),
                ('frequencyofdelivery', models.CharField(max_length=50)),
                ('effortBaseline', models.IntegerField()),
                ('nwDiagUpdatesAutomatable', models.CharField(max_length=5)),
                ('mwPrePostChecksAutomatable', models.CharField(max_length=5)),
                ('configPushAutomatable', models.CharField(max_length=5)),
                ('validationCorporateAppAutomatable', models.CharField(max_length=5)),
                ('validationPublicAppAutomatable', models.CharField(max_length=5)),
                ('nwDiagUpdatesCurrentManualEffortMin', models.IntegerField()),
                ('mwPrePostChecksCurrentManualEffortMin', models.IntegerField()),
                ('configPushCurrentManualEffortMin', models.IntegerField()),
                ('validationCorporateAppCurrentManualEffortMin', models.IntegerField()),
                ('validationPublicAppCurrentManualEffortMin', models.IntegerField()),
                ('nwDiagUpdatesCurrentFinalEffortMin', models.IntegerField()),
                ('mwPrePostChecksCurrentFinalEffortMin', models.IntegerField()),
                ('configPushCurrentFinalEffortMin', models.IntegerField()),
                ('validationCorporateAppFinalManualEffortMin', models.IntegerField()),
                ('validationPublicAppFinalManualEffortMin', models.IntegerField()),
                ('deliverableCount', models.IntegerField()),
                ('devicesPerDeliverable', models.IntegerField()),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.Dashboard_Info')),
            ],
            options={
                'db_table': 'Automation',
            },
        ),
    ]
