# Generated by Django 3.0.2 on 2021-09-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0014_auto_20210928_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceskills',
            name='technology',
        ),
    ]
