# Generated by Django 3.0.2 on 2021-09-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0016_resources_entorsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='leadCapable',
            field=models.CharField(default='No', max_length=5),
        ),
    ]
