# Generated by Django 3.0.2 on 2021-10-01 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0017_resources_leadcapable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=10)),
                ('amiFunction', models.CharField(max_length=15)),
                ('architecture', models.CharField(max_length=30)),
                ('subDomain', models.CharField(max_length=15)),
                ('technology', models.CharField(max_length=30)),
                ('qtr', models.CharField(max_length=10)),
                ('lifeCycleStage', models.CharField(max_length=50)),
                ('serviceDescription', models.CharField(max_length=50)),
                ('solutionTemplateDocument', models.CharField(max_length=50)),
                ('frequencyofdelivery', models.CharField(max_length=50)),
                ('effortBaseline', models.IntegerField()),
                ('nwDiagUpdatesAutomatable', models.CharField(max_length=5)),
                ('mwPrePostChecksAutomatable', models.CharField(max_length=5)),
                ('configPushAutomatable', models.CharField(max_length=5)),
                ('validationCorporateAppAutomatable', models.CharField(max_length=5)),
                ('validationPublicAppAutomatable', models.CharField(max_length=5)),
                ('nwDiagUpdatesCurrentManualEffortMin', models.IntegerField()),
                ('mwPrePostChecksCurrentManualEffortMin', models.IntegerField()),
                ('configPushCurrentManualEffortMin', models.IntegerField()),
                ('validationCorporateAppCurrentManualEffortMin', models.IntegerField()),
                ('validationPublicAppCurrentManualEffortMin', models.IntegerField()),
                ('nwDiagUpdatesCurrentFinalEffortMin', models.IntegerField()),
                ('mwPrePostChecksCurrentFinalEffortMin', models.IntegerField()),
                ('configPushCurrentFinalEffortMin', models.IntegerField()),
                ('validationCorporateAppFinalManualEffortMin', models.IntegerField()),
                ('validationPublicAppFinalManualEffortMin', models.IntegerField()),
                ('nwDiagUpdatesDeliverableCount', models.IntegerField()),
                ('mwPrePostChecksDeliverableCount', models.IntegerField()),
                ('configPushDeliverableCount', models.IntegerField()),
                ('validationCorporateAppDeliverableCount', models.IntegerField()),
                ('validationPublicAppDeliverableCount', models.IntegerField()),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.Dashboard_Info')),
            ],
            options={
                'db_table': 'Automation1',
            },
        ),
        migrations.DeleteModel(
            name='Automation',
        ),
    ]
