# Generated by Django 3.0.2 on 2021-10-04 11:00

import dashapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0018_auto_20211001_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('IssueID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('IssueTitle', models.CharField(max_length=50)),
                ('FunctionalBlock', models.CharField(max_length=30)),
                ('DeviceOS', models.CharField(max_length=20)),
                ('TACID', models.CharField(max_length=10)),
                ('Region', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Issue',
            },
        ),
        migrations.CreateModel(
            name='Project_Names',
            fields=[
                ('project_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('project_Name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Project_Names',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='not available', max_length=150)),
                ('Date_of_Migration', models.CharField(max_length=25)),
                ('Activity_Type', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Solution', models.CharField(max_length=500)),
                ('Lesson', models.CharField(max_length=500)),
                ('Avoidance', models.CharField(max_length=500)),
                ('Status', models.CharField(max_length=5)),
                ('Recorded_By', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=dashapp.models.filepath)),
                ('IssueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.Issue')),
                ('project', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='dashapp.Project_Names')),
            ],
            options={
                'db_table': 'Lessons',
            },
        ),
    ]
