# Generated by Django 3.0.2 on 2021-10-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0020_lessons_modelnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='Avoidance',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='Description',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='Lesson',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='Solution',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='Status',
            field=models.CharField(max_length=10),
        ),
    ]
