# Generated by Django 3.0.2 on 2022-01-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0021_auto_20211006_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_info',
            name='dealValue',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='CommentsOnScheduleResourcing',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='India_NCEs',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='accomplishments',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='automationComments',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='automationStatus',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='bookingsComment',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='cbuCfuStatus',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='customerSentiment',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='dealId',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='executionFY',
            field=models.CharField(default='FY21-22', max_length=25),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='executiveSummary',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='generalComments',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='goalsForNextMonth',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='includeForBookings',
            field=models.CharField(default='No', max_length=12),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='modified',
            field=models.CharField(default='4/30/2020  3:02:01 PM', max_length=25),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='modifiedBy',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='newProjectAudit',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='newProjectAuditDate',
            field=models.CharField(default='5/20/2020', max_length=25),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='otherRegionNCEs',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='overallStatus',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='pOneAudit',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='pOneAuditDate',
            field=models.CharField(default='5/20/2020', max_length=25),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='pOneProject',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='preSalesActivity',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='preSalesContributor',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='preSalesEffort',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='projectBookingYear',
            field=models.CharField(default='FY21', max_length=25),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='projectClass',
            field=models.CharField(default='AS-Transactional', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='projectType',
            field=models.CharField(default='Migration', max_length=40),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='qualityComments',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='qualityStatus',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='repeatBusinessRemark',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='resourceComments',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='resourceStatus',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='risksImpactAsks',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='scheduleComments',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='scheduleStatus',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='serviceDelivery',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='source',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='sourceRequesterName',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='staffing',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='technology',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='test',
            field=models.CharField(default='Shaurya Gupta', max_length=35),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='CommentsOnScheduleResourcing',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='India_NCEs',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='cbuCfuStatus',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='otherRegionNCEs',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='preSalesActivity',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='preSalesContributor',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='preSalesEffort',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='resources',
            name='manager',
            field=models.CharField(default='Anuj Kumar', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='endDate',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='repeatBusiness',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='startDate',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='accomplishments',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='automationComments',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='automationStatus',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='customerSentiment',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='executiveSummary',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='goalsForNextMonth',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='overallStatus',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='qualityComments',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='qualityStatus',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='resourceComments',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='resourceStatus',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='risksImpactAsks',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='scheduleComments',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='scheduleStatus',
            field=models.TextField(default='NA'),
        ),
    ]
